function createfigure(X1, Y1, X2, YMatrix1)
%CREATEFIGURE(X1, Y1, X2, YMatrix1)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data
%  X2:  vector of plot x data
%  YMATRIX1:  matrix of plot y data

%  Auto-generated by MATLAB on 07-Mar-2026 10:45:14

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot1 = plot(X1,Y1,'DisplayName','Observed counts','LineWidth',1.2,...
    'Color',[0 0 1]);

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot1,500,304);
% Create datatip
datatip(plot1,'DataIndex',501);

% Create multiple line objects using matrix input to plot
plot2 = plot(X2,YMatrix1,'LineWidth',2);
set(plot2(1),...
    'DisplayName','Logistic: y = 302.2328 / (1 + e^{-0.0143 (x-101.5374)})',...
    'LineStyle','--',...
    'Color',[1 0 0]);
set(plot2(2),...
    'DisplayName','Quadratic: y = -0.0006 x^2 + 0.7129 x + 93.5322',...
    'LineStyle','-.',...
    'Color',[0 1 0]);

% Create ylabel
ylabel('Number of vehicles');

% Create xlabel
xlabel('Frame number');

% Create title
title('Vehicle Growth and Fitted Models');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-3.99361022364217 996.006389776358]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[14.7706422018349 364.770642201835]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.6662955702938 0.200468984339606 0.201748793405799 0.080997756283419]);

